### ISSUE TITLE
no function clause matching in LoggerLogstashBackend.handle_event/2

### ISSUE THREAD

**Issue by henryj** [marcelog/logger_logstash_backend#11]
I think it happens in `mix test` when `use ExUnit.Case, async: false`

Here's the error msg:

10:45:58.627 [error] GenServer #PID<0.1069.0> terminating
** (FunctionClauseError) no function clause matching in LoggerLogstashBackend.handle_event/2
    lib/logger_logstash_backend.ex:28: LoggerLogstashBackend.handle_event(:flush, %{host: '192.168.0.12', level: :debug, metadata: [test: true], name: :debug_log, port: 10001, socket: #Port<0.34784>, type: "phoenix"})
    (elixir) lib/gen_event.ex:1104: GenEvent.do_handler/3
    (elixir) lib/gen_event.ex:945: GenEvent.server_update/5
    (elixir) lib/gen_event.ex:930: GenEvent.server_notify/7
    (elixir) lib/gen_event.ex:903: GenEvent.server_event/4
    (elixir) lib/gen_event.ex:709: GenEvent.handle_msg/5
    (elixir) lib/gen_event.ex:718: GenEvent.handle_msg/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:gen_event_EXIT, {LoggerLogstashBackend, :debug_log}, {:function_clause, [{LoggerLogstashBackend, :handle_event, [:flush, %{host: '192.168.0.12', level: :debug, metadata: [test: true], name: :debug_log, port: 10001, socket: #Port<0.34784>, type: "phoenix"}], [file: 'lib/logger_logstash_backend.ex', line: 28]}, {GenEvent, :do_handler, 3, [file: 'lib/gen_event.ex', line: 1104]}, {GenEvent, :server_update, 5, [file: 'lib/gen_event.ex', line: 945]}, {GenEvent, :server_notify, 7, [file: 'lib/gen_event.ex', line: 930]}, {GenEvent, :server_event, 4, [file: 'lib/gen_event.ex', line: 903]}, {GenEvent, :handle_msg, 5, [file: 'lib/gen_event.ex', line: 709]}, {GenEvent, :handle_msg, 5, [file: 'lib/gen_event.ex', line: 718]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
State: {Logger, {LoggerLogstashBackend, :debug_log}, #Reference<0.0.2.537>}

**Comment by marcelog** [comment]
Hello,

I can't reproduce this. Current tests are using `async: false` also, and according to Travis they pass in Elixirs 1.1.x, 1.2.x, and 1.3.x. Could you perhaps describe exactly how to reproduce this and which Elixir version are you using?

Thanks!

**Comment by henryj** [comment]
I'm on Elixir 1.3. 

If I test only 1 or 2 test files no matter they are async or not seems all good. But when I test a number of tests or all tests together this appears. So I assume the test running time needs to be long enough to trigger this issue.

**Comment by marcelog** [comment]
I'm still going to need more info than that :)

I've never seen this (and I've been using this project in production for about 2 years now, one of the products using this in production has about 370 tests).

I'm not denying it, but just saying that you have to dig a bit deeper and find what is causing it before trying to work on a fix.

Thanks!

**Comment by henryj** [comment]
According to https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger.ex#L228

The handle_event needs to handle both `{level, group_leader, {Logger, message, timestamp, metadata}}` and `:flush`, which I believe we only handle the former here.

**Comment by marcelog** [comment]
Yes, that's correct, and that seems to be something "new", commited on May 31st in https://github.com/elixir-lang/elixir/commit/5830699836207293eb1f574abae1271c91258f64.

A fix could be:
```
  def handle_event(:flush, state) do
    :ok
  end
```

You can try that in the meantime, since we are still only using UDP packets and nothing is buffered, there's nothing to do on a flush.

I've tried running `Logger.flush` in the console, and the issue doesn't happen, so I'm still curious about what causes it.

Could you post a use case that can reproduce it? That's needed so a test case can be written for the fix.

Thanks.

**Comment by henryj** [comment]
I'll try tomorrow. Don't have the code with me at the moment. Thanks.

On Tue, Jul 12, 2016 at 9:21 PM, Marcelo Gornstein <notifications@github.com

**Comment by marcelog** [comment]
The issue where this is discussed is useful: https://github.com/elixir-lang/elixir/pull/4728, and also logger_file_backend was updated in the same way here: https://github.com/onkel-dirtus/logger_file_backend/commit/550663ac6602999230c47ab1999c480e539090a6 so I'm opening #12 so you can try it. 

Having this change in logger_file_backend gives me some confidence to merge, so I will :) Please let me know how this worked for you.

**Comment by henryj** [comment]
Great. All good now. Thanks.

On Tue, Jul 12, 2016 at 9:43 PM, Marcelo Gornstein <notifications@github.com
